# This workflow will install Python dependencies, runs the script at 02:40 and 12:40 UTC every day.

name: Python application

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    # 此处是UTC时间 即北京时间 -8小时
    - cron: '40 2,12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        pip install -r requirements.txt
    - name: Run
      run: |
        python main.py
    - name: commit
      run: |
         git config --local user.email "leejianzhao@gmail.com"
         git config --local user.name "Leo-Leejianzhao"
         git add subscribe/v2ray.txt
         git add subscribe/v2ray_mat.txt
         git add subscribe/clash.yml
         git add subscribe/clash_mat.yml
         git commit -m "更新订阅链接"
    - name: push
      uses:  ad-m/github-push-action@master
      with:
         # github_token: ${{ secrets.TOKEN }}
         branch: main
