# This workflow will install Python dependencies, runs the script at 02:40 and 12:40 UTC every day.

name: Python application

on: [push]
#   schedule:
#     # - cron: '*/5 * * * *'
#     # 表达式生成  https://crontab.guru/
#     # 此处是UTC时间 即北京时间 -8小时
#     - cron: '40 2,12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        pip install -r requirements.txt
    - name: Run
      run: |
        python main.py
    - name: 提交更改
      run: |
         git config --local user.email "leejianzhao@gmail.com"
         git config --local user.name "Leo-Leejianzhao"
         git add subscribe/v2ray.txt
         git add subscribe/clash.yml
         git commit -m "更新订阅链接"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         # github_token: ${{ secrets.TOKEN }}
         branch: main